#version: '3.8'

services:
  spark-master:
    image: spark:latest
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"  # Spark Master Web UI
      - "4040:4040"  # Spark Master Web UI
      - "7077:7077"  # Spark Master Port
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    networks:
      - spark-network
    volumes:
      - ./data:/opt/spark/work-dir/data
      - ./spark-apps:/opt/spark/work-dir/apps
      - spark-master-data:/opt/spark/data-persist
    command: >
      bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master"

  spark-worker-1:
    image: spark:latest
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"  # Worker 1 Web UI
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_WEBUI_PORT=8081
    networks:
      - spark-network
    volumes:
      - ./data:/opt/spark/work-dir/data
      - ./spark-apps:/opt/spark/work-dir/apps
      - spark-worker-1-data:/opt/spark/data-persist
    command: >
      bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"

  spark-worker-2:
    image: spark:latest
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"  # Worker 2 Web UI
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=4g
      - SPARK_WORKER_WEBUI_PORT=8081
    networks:
      - spark-network
    volumes:
      - ./data:/opt/spark/work-dir/data
      - ./spark-apps:/opt/spark/work-dir/apps
      - spark-worker-2-data:/opt/spark/data-persist
    command: >
      bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"

networks:
  spark-network:
    driver: bridge

volumes:
  spark-master-data:
  spark-worker-1-data:
  spark-worker-2-data:
